[env:m5stack-cores3]
platform  = espressif32
board     = m5stack-cores3
framework = arduino

monitor_speed   = 115200
upload_speed    = 1500000
monitor_filters = esp32_exception_decoder

build_unflags = -std=gnu++11

build_flags =
  -DBOARD_HAS_PSRAM
  -DCORE_DEBUG_LEVEL=1
  -std=gnu++17
  -fpermissive
  -DUART_SCLK_DEFAULT=UART_SCLK_XTAL

lib_deps =
  m5stack/M5Unified
  https://github.com/m5stack/StackChan-BSP.git
  https://github.com/iceyman/m5stack-avatar.git
  bblanchon/ArduinoJson @ ^7.0.4
  esp32-camera

build_src_filter = +<main.cpp> +<wifi_networks.h> +<dance_music.h>

[env:m5stack-cores3-ota-robot2]
extends         = env:m5stack-cores3
upload_protocol = espota
upload_port     = robot2.local
upload_flags    = --auth=YOUR_OTA_PASSWORD

[env:m5stack-cores3-ota-robot1]
extends         = env:m5stack-cores3
upload_protocol = espota
upload_port     = robot1.local
upload_flags    = --auth=YOUR_OTA_PASSWORD

[env:m5stack-cores3-servo-test]
extends          = env:m5stack-cores3
build_src_filter = +<servo_test.cpp>

[env:m5stack-cores3-diag]
extends          = env:m5stack-cores3
build_src_filter = +<diagnostic_main.cpp>
